language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAIA2RP3OMUCHSYPGA
  secret_access_key:
    secure: tiaw21uA9CwRKa1JvSY7nkCkw6YwuGiXa7eXLkr+FnfO+kiYFRkL02XEg6t/Zu6uk0ekX51OxNxK9QK1FbSmqM1RuuL5ZtGrqK9MSOW0fQ0D9WA8jNY7HwZh/1WqUjW0UXKel7XvNzUxZWMbMGYgC7u1NT+R+mtXNj4jEY17olYPQZ3wiegdXT9U0QmybQ0Me59hMqJntSad6KEDxVU370/blw/y9Zvsv3p0zneu8aiy3cawlzqEoThkEP/r4eKAcHRv+0vHAMnxImvXFcK6EFmMleC3WI2uyHh+HAIjiRONdwm2uUouy3j1amA5G+hlJ7WAPup/8UEhx9F5Z26SBcsw2C4XoVZMvlG/MyeoxmPK3epdxfdUioDWOsMQ/5Jl9R91jv3EUU6Iid6Qr9fDlEGUmPIja2nT1Vu4GhfS1mz60ZiHwujT33LDgNQsPJ6lji8pIn41C/+YClPB/04kVzxhxrpE6NA/uAwj7P54erfrIBsWhBoZi/4vi1CP0bPCsVDvgdgchcblD80f2NilPfEXsHA0PYClAH9OcHJHQpAeobe5rNPaj1keKlVpwd5xSQA+ApUmk3HB42KNi/Lh5iaWNDuU5hs1iFjW0g6n8ZdCUp9cViX7jADlvt1AoG4KFZupQ/ZFla9x8lcCS46ePHpxCqiAQ/X9HM5mJqyI+QQ=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: vadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/vadictionary
    all_branches: true
