language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAIA2RP3OMUCHSYPGA
  secret_access_key:
    secure: TlKHROwc2dSOsMB+GMv0CPL9VYaISrgrjCI1DFtynmdUR6cShMwd3oydK6vnyXqbK+h0GHwSyKUV6NxMYeFMHzqG8x5w/23QhJXupulRYEYPamDp1fQicbF+UMaafEP/8cJV/15BmgZjT775nHJ+c0Q+Uwa+yibyM+vpep1iidcTob7wj6/wxm/9UkG7gETJP16S/CcrijQV76sFXblXwkwA9qeEPH8JYTuYUhr+oTsEVDoVoofAB4n0qHNHPKu4vs1WLi9dr0rrg1+umuY9tUpk0+rdE8rgF26+LS/dDEoe4muSD5mnXyjpcGWKd9MP7EuCrr2YoDxtadFDLTdTunSvotuSQMMzVOwxZEEnTu9/9SF4FDGHZAIb4FvB0S2McNXQohHStKzk2JsLl4Xv2BCLvzV1/JKB5ATQ/+QtuWAOQCg8JJ0RIkXMMk953oZgULSunnBir4PX/2wjrb0H8ktFYM0mc8r02U+/wxeGhATSPIINARuBdm71mAW71T23LlzbikgikiB8oR3G4zcxISfS6nz34/ZkKS7rTC4RDaXmyDNdAneiT7NlXvQUPvg6+x1vMuCCH6quECbtPseqGx4WgKnxjApVSrqSv5FhYoUtb8yTPU8DXMb9J7C55viNFRr0t9FZVQLs31WfEwpxR2UfEuVQ4BxezuhMwHqjvPg=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: vadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/vadictionary
    all_branches: true
